# Site settings
title: Bart van Zeist
description: Hi, I am Bart 👋. I am a twenty-year-old, Dutch, software engineer.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Bart van Zeist
user_title: Software Engineer

exclude: ["package.json", "src", "node_modules"]

